Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false        # Disabled to support older ruby versions
Style/MutableConstant:
  Enabled: false
Style/FormatString:
  Enabled: false

Lint/RescueException:
  Enabled: false
Lint/InheritException:
  Enabled: false

# Disabling these new cops to keep parity with older Rubocop used for Ruby <=
# 3.0. Ideally, each of these should be checked, to choose whether to fix the
# offenses and enable it, or keep it disabled.
Lint/ScriptPermission:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/RedundantRequireStatement:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/ClassEqualityComparison:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/LineLength:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Lint/Void:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

# TODO: Enable this and fix offenses
Metrics:
  Enabled: false

AllCops:
  Include:
    - 'lib/**/*'
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'mqtt.gemspec'
    - 'examples/**'
    - 'spec/**/*'
    - 'vendor/**/*'
